### PR TITLE
Pass cancellation token to methods that support it.

### PR DESCRIPTION
**Pull request by Danghor**
At several places, a cancellation token was being passed to a method, but the method did not pass this cancellation token to other methods that would have supported it. I fixed those place by passing the cancellation token wherever possible.

### CODE REVIEW

**Comment by JosefPihrt** [comment]
I'm curious: did you use some analyzer to detect it?

**Comment by Danghor** [comment]
ReSharper... 😅

**Comment by JosefPihrt** [comment]
Thanks!

**Comment by jnyrup** [comment]
@JosefPihrt https://github.com/u2uconsult/codeanalyzers/blob/master/docs/U2U1016.md has a similar feature.

**Pull request merged**
