### PR TITLE
Code fixes

### PR DESCRIPTION
**Pull request by jnyrup**
I have found and fixed what I believe to be errors in the code.

Note that I haven't done any testing of it.

### CODE REVIEW

**Comment by jnyrup** [comment]
Damn... I was unsure about that commit. 

I'm not yet familiar enough with the CodeAnalysis framework to know hot to simply fix this.

But the problem is that 
```csharp
if (kind == SyntaxKind.ThisExpression
	|| kind != SyntaxKind.SimpleMemberAccessExpression)
{
	return methodSymbol;
}
```
will pass no matter if `kind == SyntaxKind.ThisExpression` is true or not.

**Comment by JosefPihrt** [comment]
You are right that the condition is incorrect. It should look like this:

```csharp
if (!expression.IsKind(SyntaxKind.SimpleMemberAccessExpression)
    || ((MemberAccessExpressionSyntax)expression).Expression.IsKind(SyntaxKind.ThisExpression))
{
    return methodSymbol;
}
```
(If the invocation expression is qualified then it must be qualified with `this`.)

**Comment by JosefPihrt** [comment]
You are right that the condition is incorrect. It should look like this:

```csharp
if (!expression.IsKind(SyntaxKind.SimpleMemberAccessExpression)
    || ((MemberAccessExpressionSyntax)expression).Expression.IsKind(SyntaxKind.ThisExpression))
{
    return methodSymbol;
}
```
(If the invocation expression is qualified then it must be qualified with `this`.)

**Comment by JosefPihrt** [comment]
Thanks for a contribution!

**Pull request merged**
