### PR TITLE
UseAnyMethodInsteadOfCountMethod with >= 1

### PR DESCRIPTION
**Pull request by jnyrup**
This PR adds support for replacing `Count() >= 1` with `Any()`.

I've tested it by installing the generated vsix and visually inspect that they work as inspected in the RoslynatorTests solution.
Please let me know if I'm missing out on a more automatic test procedure.

### CODE REVIEW

**Comment by jnyrup** [comment]
Let me know, if you prefer the commits to be squashed.

**Comment by JosefPihrt** [comment]
I can squash it by selecting "Squash and merge" option, right?

**Comment by jnyrup** [comment]
I did not know there was such an option.
Then just use that.

**Comment by JosefPihrt** [comment]
Thanks for the contribution!

**Comment by jnyrup** [comment]
You're welcome. 
It's a joy to contribute to such pretty code.

**Pull request merged**
