### PR TITLE
Update RCS1166.md

### PR DESCRIPTION
**Pull request by xtqqczze**
Add additional example for a non-numeric type in documentation for `RCS1166: Value type object is never equal to null`.

### CODE REVIEW

**Comment by JosefPihrt** [comment]
The current fix replaces `null` with `0` not `default`. Am I missing something?

**Comment by xtqqczze** [comment]
> 
> 
> The current fix replaces `null` with `0` not `default`. Am I missing something?

https://github.com/xtqqczze/PowerShell/commit/4c33ee0dee4539c56a03c42a45b7141ed6316891

**Comment by xtqqczze** [comment]
@JosefPihrt My bad, I missed in your example `x` is type `int`, so `0` would be correct.

**Comment by xtqqczze** [comment]
I think the example is more helpful with a non-numeric type like `IntPtr` where it is less obvious it is never equal to null.

**Comment by JosefPihrt** [comment]
I'm fine with adding another example, I don't think it is necessary to overwrite original example.

**Comment by xtqqczze** [comment]
@JosefPihrt New example added, my branch is open if you want to make any changes.

**Comment by JosefPihrt** [comment]
I forgot to tell you that the file you edited is actually generated.

Please follow [these](https://github.com/JosefPihrt/Roslynator/blob/master/docs/HowToUpdateDocumentation.md) instructions.

**Comment by xtqqczze** [comment]
@JosefPihrt updated

**Pull request merged**
